version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:9.5.0-stretch

    working_directory: ~/circleci-demo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test
      - store_test_results:
          path: test-results
      - run: npm run build

  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/circleci-demo
    steps:
      - run: npm install firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: ln -s ./node_modules/.bin/firebase . && \
    ./firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
            
workflows:
  version: 2
  
  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
